-- D1 schema for a provider-agnostic transactional email system.
-- Design goal: nothing here references Resend/Postmark/SendGrid/etc by name.
-- The provider is just a string label + whatever id it handed back.

-- One row per logical email you asked the system to send.
-- This is your source of truth, independent of which provider actually
-- moved it — if you switch providers next month, history still reads fine.
CREATE TABLE IF NOT EXISTS emails (
  id            TEXT PRIMARY KEY,               -- uuid, generated by the Worker
  to_address    TEXT NOT NULL,
  from_address  TEXT NOT NULL,
  reply_to      TEXT,
  subject       TEXT NOT NULL,
  template_key  TEXT,                           -- e.g. 'welcome', 'password_reset'; null for ad-hoc sends
  template_data TEXT,                            -- JSON blob of template variables
  html_body     TEXT,                            -- rendered body, kept for audit/resend even if a template was used
  text_body     TEXT,
  status        TEXT NOT NULL DEFAULT 'queued',  -- queued | sending | sent | failed | bounced
  provider      TEXT,                            -- 'resend' | 'postmark' | 'sendgrid' | 'console' | ...
  provider_message_id TEXT,                      -- the id the provider gave back, for webhook correlation
  error         TEXT,                            -- last error message, if any
  attempts      INTEGER NOT NULL DEFAULT 0,
  max_attempts  INTEGER NOT NULL DEFAULT 3,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now')),
  sent_at       TEXT
);

CREATE INDEX IF NOT EXISTS idx_emails_status ON emails (status);
CREATE INDEX IF NOT EXISTS idx_emails_to ON emails (to_address);
CREATE INDEX IF NOT EXISTS idx_emails_created_at ON emails (created_at);

-- Provider-reported events (delivered, opened, bounced, complained...).
-- Kept separate from `emails` because different providers report different
-- event sets and you don't want that variability leaking into the core table.
CREATE TABLE IF NOT EXISTS email_events (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  email_id      TEXT NOT NULL REFERENCES emails(id),
  event_type    TEXT NOT NULL,                   -- 'delivered' | 'opened' | 'clicked' | 'bounced' | 'complained' | ...
  provider      TEXT NOT NULL,
  raw_payload   TEXT,                            -- original webhook JSON, for debugging
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_email_events_email_id ON email_events (email_id);

-- Simple suppression list (unsubscribes, hard bounces, complaints).
-- Checked before sending regardless of which provider ends up used.
CREATE TABLE IF NOT EXISTS email_suppressions (
  address     TEXT PRIMARY KEY,
  reason      TEXT NOT NULL,                     -- 'unsubscribed' | 'bounced' | 'complained' | 'manual'
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);
